/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.pagamento.view;

import br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication;
import br.com.ifba.prg03projeto.mercado.pagamento.controller.PagamentoController;
import br.com.ifba.prg03projeto.mercado.pagamento.entity.Pagamento;
import br.com.ifba.prg03projeto.mercado.venda.controller.VendaController;
import br.com.ifba.prg03projeto.mercado.venda.entity.Venda;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Davi
 */
public class PagamentoView extends javax.swing.JFrame {
    
    
    private final PagamentoController pagamentoController;
    private final VendaController vendaController;
    private final Long vendaId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagamentoView.class.getName());

    /**
     * Creates new form PagamentoView
     */
    public PagamentoView(Long vendaId) {
        initComponents();
        this.vendaId = vendaId;

        this.pagamentoController =
            Prg03sistemaMercadoApplication.contexto
                    .getBean(PagamentoController.class);

         this.vendaController =
            Prg03sistemaMercadoApplication.contexto
                    .getBean(VendaController.class);

    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    setLocationRelativeTo(null);

    txtValorTotal.setEditable(false);
    txtTroco.setEditable(false);

    lblVenda.setText("Venda: " + vendaId);

    loadVenda();
    loadTable();
    txtValorPago.setEditable(true);
    txtValorPago.setEnabled(true);
    txtValorPago.requestFocusInWindow();
    }
    
    private void clearForm() {
    cboFormaPagamento.setSelectedItem("DINHEIRO");
    txtValorPago.setText("");
    txtTroco.setText("");
    }
    
    private void loadVenda() {
    Venda venda = vendaController.findById(vendaId)
            .orElseThrow(() ->
                    new RuntimeException("Venda não encontrada.")
            );

    txtValorTotal.setText(
            venda.getValorTotal()
                    .toString()
                    .replace(".", ",")
    );
    }
    private void loadTable() {
    DefaultTableModel model =
            (DefaultTableModel) tblPagamentos.getModel();

    model.setRowCount(0);

    List<Pagamento> pagamentos =
            pagamentoController.findAll();

    DateTimeFormatter formatter =
            DateTimeFormatter.ofPattern(
                    "dd/MM/yyyy HH:mm"
            );

    for (Pagamento pagamento : pagamentos) {
        if (!pagamento.getVenda().getId().equals(vendaId)) {
            continue;
        }

        String dataFormatada = "";

        if (pagamento.getDataPagamento() != null) {
            dataFormatada =
                    pagamento.getDataPagamento()
                            .format(formatter);
        }

        model.addRow(new Object[]{
            pagamento.getId(),
            pagamento.getVenda().getId(),
            pagamento.getFormaPagamento(),
            pagamento.getValorPago(),
            pagamento.getTroco(),
            dataFormatada
        });
    }
}
    
    private void calcularTrocoVisual() {
    try {
        BigDecimal valorTotal = new BigDecimal(
                txtValorTotal.getText()
                        .replace(",", ".")
        );

        BigDecimal valorPago = new BigDecimal(
                txtValorPago.getText()
                        .replace(",", ".")
        );

        BigDecimal troco =
                valorPago.subtract(valorTotal);

        txtTroco.setText(
                troco.toString().replace(".", ",")
        );

    } catch (NumberFormatException exception) {
        txtTroco.setText("");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorTotal = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFormaPagamento = new javax.swing.JLabel();
        lblValorPago = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblVenda = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        cboFormaPagamento = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblValorTotal.setText("Valor Total:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("PAGAMENTO");

        lblFormaPagamento.setText("Forma Pagamento:");

        lblValorPago.setText("Valor Pago:");

        lblTroco.setText("Troco:");

        lblVenda.setText("Venda:");

        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyReleased(evt);
            }
        });

        cboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO", "PIX", "CARTAO_DEBITO", "CARTAO_CREDITO" }));

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        tblPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Venda", "Forma", "Valor Pago", "Troco", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPagamentos.setColumnSelectionAllowed(true);
        tblPagamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPagamentos);
        tblPagamentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lblTitulo))
                            .addComponent(lblFormaPagamento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorTotal)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorPago)
                            .addComponent(lblTroco)
                            .addComponent(lblVenda)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValorPago, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnPagar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnAtualizar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(lblVenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValorPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    
        loadVenda();
        loadTable();

        JOptionPane.showMessageDialog(
            this,
            "Lista de pagamentos atualizada!"
    );
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyReleased
    
        calcularTrocoVisual();
    }//GEN-LAST:event_txtValorPagoKeyReleased

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
    
        try {
        String formaPagamento =
                cboFormaPagamento
                        .getSelectedItem()
                        .toString();

        BigDecimal valorPago = new BigDecimal(
                txtValorPago.getText()
                        .replace(",", ".")
        );

        pagamentoController.registrarPagamento(
                vendaId,
                formaPagamento,
                valorPago
        );

        loadVenda();
        loadTable();
        clearForm();

        JOptionPane.showMessageDialog(
                this,
                "Pagamento registrado com sucesso!"
        );

    } catch (NumberFormatException exception) {
        JOptionPane.showMessageDialog(
                this,
                "Informe um valor pago válido.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (RuntimeException exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    
        clearForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cboFormaPagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTable tblPagamentos;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorPago;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
