/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.dashboard.view;

/**
 *
 * @author Davi
 */
public class DashboardView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardView.class.getName());

    /**
     * Creates new form DashboardView
     */
    public DashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblControleEstoque = new javax.swing.JLabel();
        lblOperacaoVendas = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnItensVenda = new javax.swing.JButton();
        btnFiliais = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnPagamentos1 = new javax.swing.JButton();
        btnSolicitacoes = new javax.swing.JButton();
        btnEstoques = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo.setText("SISTEMA DE GESTÃO DE SUPERMERCADO");

        lblControleEstoque.setText("📦 CONTROLE DE ESTOQUE");

        lblOperacaoVendas.setText("💰 OPERAÇÃO DE VENDAS");

        btnUsuarios.setText("USUÁRIOS");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnVendas.setText("VENDAS");
        btnVendas.addActionListener(this::btnVendasActionPerformed);

        btnItensVenda.setText("ITENS DA VENDA");
        btnItensVenda.addActionListener(this::btnItensVendaActionPerformed);

        btnFiliais.setText("FILIAIS");
        btnFiliais.addActionListener(this::btnFiliaisActionPerformed);

        btnProdutos.setText("PRODUTOS");
        btnProdutos.addActionListener(this::btnProdutosActionPerformed);

        btnPagamentos1.setText("PAGAMENTOS");
        btnPagamentos1.addActionListener(this::btnPagamentos1ActionPerformed);

        btnSolicitacoes.setText("SOLICITAÇÕES");
        btnSolicitacoes.addActionListener(this::btnSolicitacoesActionPerformed);

        btnEstoques.setText("ESTOQUES");
        btnEstoques.addActionListener(this::btnEstoquesActionPerformed);

        btnSair.setText("SAIR");
        btnSair.addActionListener(this::btnSairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOperacaoVendas)
                            .addComponent(lblControleEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProdutos)
                                    .addComponent(btnFiliais))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSolicitacoes)
                                    .addComponent(btnEstoques)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsuarios)
                            .addComponent(btnPagamentos1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnItensVenda)
                            .addComponent(btnVendas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnSair)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblControleEstoque)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutos)
                    .addComponent(btnSolicitacoes))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiliais)
                    .addComponent(btnEstoques))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOperacaoVendas)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios)
                    .addComponent(btnItensVenda))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVendas)
                    .addComponent(btnPagamentos1))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
    
        new br.com.ifba.prg03projeto.mercado.produto.view.ProdutoListar()
            .setVisible(true);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiliaisActionPerformed
    
         new br.com.ifba.prg03projeto.mercado.filial.view.FilialView()
            .setVisible(true);
    }//GEN-LAST:event_btnFiliaisActionPerformed

    private void btnEstoquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoquesActionPerformed
    
           new br.com.ifba.prg03projeto.mercado.estoquefilial.view.EstoqueFilialView()
            .setVisible(true);
    }//GEN-LAST:event_btnEstoquesActionPerformed

    private void btnSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitacoesActionPerformed
    
          new br.com.ifba.prg03projeto.mercado.solicitacaoreposicao.view.SolicitacaoReposicaoView()
            .setVisible(true);
    }//GEN-LAST:event_btnSolicitacoesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
    
    new br.com.ifba.prg03projeto.mercado.usuario.view.UsuarioView()
            .setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPagamentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentos1ActionPerformed
    
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Módulo em desenvolvimento."
    );
    }//GEN-LAST:event_btnPagamentos1ActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
    
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Módulo em desenvolvimento."
    );
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnItensVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItensVendaActionPerformed
    
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Módulo em desenvolvimento."
    );
    }//GEN-LAST:event_btnItensVendaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstoques;
    private javax.swing.JButton btnFiliais;
    private javax.swing.JButton btnItensVenda;
    private javax.swing.JButton btnPagamentos1;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSolicitacoes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVendas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblControleEstoque;
    private javax.swing.JLabel lblOperacaoVendas;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
