/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.produto.view;

import br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication;
import br.com.ifba.prg03projeto.mercado.produto.controller.ProdutoController;
import br.com.ifba.prg03projeto.mercado.produto.entity.Produto;
import br.com.ifba.prg03projeto.mercado.estoquefilial.view.EstoqueFilialView;
import br.com.ifba.prg03projeto.mercado.filial.view.FilialView;
import br.com.ifba.prg03projeto.mercado.view.SolicitacaoReposicaoView;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Davi
 */
public class ProdutoListar extends javax.swing.JFrame {
    
    
    private final ProdutoController produtoController; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoListar.class.getName());

    /**
     * Creates new form ProdutoListar
     */
    public ProdutoListar() {
    
        initComponents();

    produtoController = Prg03sistemaMercadoApplication.contexto
            .getBean(ProdutoController.class);

    carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnFiliais = new javax.swing.JButton();
        btnEstoques = new javax.swing.JButton();
        btnSolicitacoes = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setText("GERENCIAMENTO DE PRODUTOS");

        lblBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBusca.setText("BUSCAR:");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        btnNovo.setText("+");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Código de Barras", "Preço", "Estoque Mínimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        btnFiliais.setText("FILIAIS");
        btnFiliais.addActionListener(this::btnFiliaisActionPerformed);

        btnEstoques.setText("ESTOQUES");
        btnEstoques.addActionListener(this::btnEstoquesActionPerformed);

        btnSolicitacoes.setText("SOLICITAÇÕES");
        btnSolicitacoes.addActionListener(this::btnSolicitacoesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBusca)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFiliais)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEstoques)
                            .addComponent(btnSolicitacoes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovo))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(34, 34, 34)
                .addComponent(btnFiliais)
                .addGap(18, 18, 18)
                .addComponent(btnEstoques)
                .addGap(18, 18, 18)
                .addComponent(btnSolicitacoes)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        
         carregarTabelaFiltro(txtBusca.getText());
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        // Atualiza os dados da tabela.
        carregarTabela();

        // Exibe mensagem para o usuário.
        javax.swing.JOptionPane.showMessageDialog(
        this,
        "Produtos atualizados com sucesso!",
        "Informação",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        carregarTabelaFiltro(txtBusca.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

    int linha = tblProdutos.getSelectedRow();

    if (linha < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Selecione um produto para remover!",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja remover este produto?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmacao != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        Long id = Long.valueOf(tblProdutos.getValueAt(linha, 0).toString());

        produtoController.delete(id);

        carregarTabela();

        JOptionPane.showMessageDialog(
                this,
                "Produto removido com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Erro ao remover produto: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       
        ProdutoSave tela = new ProdutoSave();
        tela.setLocationRelativeTo(this);
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int linha = tblProdutos.getSelectedRow();

    if (linha < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Selecione um produto para editar!",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    Long id = Long.valueOf(tblProdutos.getValueAt(linha, 0).toString());

    produtoController.findById(id).ifPresentOrElse(
            produtoEncontrado -> {
                ProdutoSave tela = new ProdutoSave(produtoEncontrado);
                tela.setLocationRelativeTo(this);
                tela.setVisible(true);
            },
            () -> JOptionPane.showMessageDialog(
                    this,
                    "Produto não encontrado!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            )
    );
      
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnFiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiliaisActionPerformed
    
     // Abre a tela de gerenciamento de filiais.
    new FilialView().setVisible(true);    
        
    }//GEN-LAST:event_btnFiliaisActionPerformed

    private void btnEstoquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoquesActionPerformed
    
        // Abre a tela de gerenciamento de estoques das filiais.
    new EstoqueFilialView().setVisible(true);
    
    }//GEN-LAST:event_btnEstoquesActionPerformed

    private void btnSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitacoesActionPerformed
    
     // Abre a tela de solicitações de reposição.
    new SolicitacaoReposicaoView().setVisible(true);    
        
    }//GEN-LAST:event_btnSolicitacoesActionPerformed

    // Carrega todos os produtos cadastrados na tabela.
private void carregarTabela() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblProdutos.getModel();

    modelo.setRowCount(0);

    List<Produto> lista = produtoController.findAll();

    for (Produto produto : lista) {
        modelo.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            produto.getCodigoBarras(),
            produto.getPreco(),
            produto.getEstoqueMinimo()
        });
    }
}

// Carrega a tabela filtrando os produtos pelo nome.
private void carregarTabelaFiltro(String texto) {

    DefaultTableModel modelo =
            (DefaultTableModel) tblProdutos.getModel();

    modelo.setRowCount(0);

    List<Produto> lista = produtoController.findByNome(texto);

    for (Produto produto : lista) {
        modelo.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            produto.getCodigoBarras(),
            produto.getPreco(),
            produto.getEstoqueMinimo()
        });
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEstoques;
    private javax.swing.JButton btnFiliais;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSolicitacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
