spring.application.name=prg03sistema-mercado

spring.datasource.url=jdbc:postgresql://db.jerqzercztekeqyrfrbn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=iAV22IX8EwRgpcna

# Atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Exibe SQL no console
spring.jpa.show-sql=true
# Formata SQL
spring.jpa.properties.hibernate.format_sql=true
# Dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect