/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.venda.view;
import br.com.ifba.prg03projeto.mercado.usuario.session.SessaoUsuario;
import br.com.ifba.prg03projeto.mercado.venda.controller.VendaController;
import br.com.ifba.prg03projeto.mercado.venda.entity.Venda;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication;
import br.com.ifba.prg03projeto.mercado.itemvenda.view.ItemVendaView;


/**
 *
 * @author Davi
 */
public class VendaView extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(
                    VendaView.class.getName()
            );

    private final VendaController vendaController;
    private Long vendaSelecionadaId;

    public VendaView() {
        initComponents();

        this.vendaController =
        Prg03sistemaMercadoApplication.contexto
                .getBean(VendaController.class);

        setLocationRelativeTo(null);
        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        lblNomeUsuario.setText(
                SessaoUsuario.getUsuarioLogado().getNome()
        );
        
        cboStatus.setEnabled(false);
        txtValorTotal.setEditable(false);

        loadTable();
        clearForm();
    }

    private void fillForm(Venda venda) {
        vendaSelecionadaId = venda.getId();

        cboStatus.setSelectedItem(venda.getStatus());

        txtValorTotal.setText(
                venda.getValorTotal()
                        .toString()
                        .replace(".", ",")
        );

        
    }

    private void clearForm() {
        
    vendaSelecionadaId = null;

    cboStatus.setSelectedItem("EM_ANDAMENTO");

    txtValorTotal.setText("0,00");

    tblVendas.clearSelection();

    }

    private void loadTable() {
        DefaultTableModel model =
                (DefaultTableModel) tblVendas.getModel();

        model.setRowCount(0);

        DateTimeFormatter formatter =
                DateTimeFormatter.ofPattern(
                        "dd/MM/yyyy HH:mm"
                );

        for (Venda venda : vendaController.findAll()) {
            String dataFormatada = "";

            if (venda.getDataVenda() != null) {
                dataFormatada =
                        venda.getDataVenda().format(formatter);
            }

            model.addRow(new Object[]{
                venda.getId(),
                dataFormatada,
                venda.getUsuario().getNome(),
                venda.getStatus(),
                venda.getValorTotal()
            });
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUsuarioLogado = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        txtValorTotal = new javax.swing.JTextField();
        btnIniciarVenda = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnItens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTitulo.setText("GERENCIAMENTO DE VENDAS");

        lblUsuarioLogado.setText("Usuário Logado:");

        lblNomeUsuario.setText("nome");

        lblStatus.setText("Status:");

        lblValorTotal.setText("Valor Total:");

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EM_ANDAMENTO", "CONCLUIDA", "CANCELADA" }));
        cboStatus.addActionListener(this::cboStatusActionPerformed);

        txtValorTotal.setText("0,00");

        btnIniciarVenda.setText("INICIAR VENDA");
        btnIniciarVenda.addActionListener(this::btnIniciarVendaActionPerformed);

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Usuário", "Status", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVendas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblVendas);
        tblVendas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        btnItens.setText("ITENS");
        btnItens.addActionListener(this::btnItensActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeUsuario)
                            .addComponent(lblUsuarioLogado)
                            .addComponent(lblStatus)
                            .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorTotal)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnIniciarVenda)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnItens))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblTitulo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarVenda)
                    .addComponent(btnLimpar)
                    .addComponent(btnItens))
                .addGap(31, 31, 31)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar)
                    .addComponent(btnRemover))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboStatusActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        
          loadTable();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Lista de vendas atualizada com sucesso!",
            "Informação",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVendaActionPerformed
    
         try {

        Venda venda = vendaController.iniciarVenda();

        fillForm(venda);

        loadTable();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Venda iniciada com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnIniciarVendaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    
        int linha = tblVendas.getSelectedRow();

    if (linha < 0) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione uma venda.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    Long id = Long.valueOf(
            tblVendas.getValueAt(linha, 0).toString()
    );

    Venda venda = vendaController.findById(id).orElse(null);

    if (venda != null) {
        fillForm(venda);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    
        if (vendaSelecionadaId == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione uma venda.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {

        vendaController.cancelar(vendaSelecionadaId);

        loadTable();
        clearForm();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Venda cancelada com sucesso!"
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       clearForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
    
         if (vendaSelecionadaId == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione uma venda.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int opcao = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente remover a venda?",
            "Confirmação",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (opcao != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    try {

        vendaController.delete(vendaSelecionadaId);

        loadTable();
        clearForm();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Venda removida com sucesso!"
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItensActionPerformed
    
        try {
        if (vendaSelecionadaId == null) {
            throw new RuntimeException(
                    "Selecione uma venda para gerenciar os itens."
            );
        }

        Venda venda = vendaController.findById(vendaSelecionadaId)
                .orElseThrow(() ->
                        new RuntimeException("Venda não encontrada.")
                );

        if (!"EM_ANDAMENTO".equals(venda.getStatus())) {
            throw new RuntimeException(
                    "Somente vendas em andamento podem receber itens."
            );
        }

        new ItemVendaView(vendaSelecionadaId).setVisible(true);

    } catch (RuntimeException exception) {
        javax.swing.JOptionPane.showMessageDialog(
        this,
        exception.getMessage(),
        "Erro",
        javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnItensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VendaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnIniciarVenda;
    private javax.swing.JButton btnItens;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
