package br.com.ifba.prg03projeto.mercado.itemvenda.view;

import br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication;
import br.com.ifba.prg03projeto.mercado.itemvenda.controller.ItemVendaController;
import br.com.ifba.prg03projeto.mercado.itemvenda.entity.ItemVenda;
import br.com.ifba.prg03projeto.mercado.produto.controller.ProdutoController;
import br.com.ifba.prg03projeto.mercado.produto.entity.Produto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ItemVendaView extends javax.swing.JFrame {

    private final ItemVendaController itemVendaController;
    private final ProdutoController produtoController;

    private final Long vendaId;

    private Long itemSelecionadoId;

    public ItemVendaView(Long vendaId) {
        initComponents();

        this.vendaId = vendaId;

        this.itemVendaController =
                Prg03sistemaMercadoApplication.contexto
                        .getBean(ItemVendaController.class);

        this.produtoController =
                Prg03sistemaMercadoApplication.contexto
                        .getBean(ProdutoController.class);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        txtPrecoUnitario.setEditable(false);
        txtSubtotal.setEditable(false);

        tblItens.setSelectionMode(
                javax.swing.ListSelectionModel.SINGLE_SELECTION
        );

        lblVenda.setText("Venda: " + vendaId);

        loadProdutos();
        loadTable();
    }

    private void loadProdutos() {
        cboProduto.removeAllItems();

        List<Produto> produtos = produtoController.findAll();

        for (Produto produto : produtos) {
            cboProduto.addItem(produto);
        }
    }

    private void loadTable() {
        DefaultTableModel model =
                (DefaultTableModel) tblItens.getModel();

        model.setRowCount(0);

        List<ItemVenda> itens =
                itemVendaController.findByVendaId(vendaId);

        for (ItemVenda item : itens) {
            model.addRow(new Object[]{
                item.getId(),
                item.getProduto().getNome(),
                item.getQuantidade(),
                String.format("%.2f", item.getPrecoUnitario()),
                String.format("%.2f", item.getSubtotal())
            });
        }
    }

    private void clearForm() {
        
    itemSelecionadoId = null;

    txtQuantidade.setText("");
    txtSubtotal.setText("");

    cboProduto.setEnabled(true);
    tblItens.clearSelection();

    if (cboProduto.getItemCount() > 0) {
        cboProduto.setSelectedIndex(0);

        Produto produto =
                (Produto) cboProduto.getSelectedItem();

        if (produto != null) {
            txtPrecoUnitario.setText(
                    String.format("%.2f", produto.getPreco())
            );
        }
    } else {
        txtPrecoUnitario.setText("");
    }
    btnAdicionar.setText("ADICIONAR");
        
    }

    private void calcularSubtotalVisual() {
        try {
            Produto produto =
                    (Produto) cboProduto.getSelectedItem();

            if (produto == null) {
                txtPrecoUnitario.setText("");
                txtSubtotal.setText("");
                return;
            }

            txtPrecoUnitario.setText(
                    String.format("%.2f", produto.getPreco())
            );

            Integer quantidade =
                    Integer.valueOf(txtQuantidade.getText());

            double subtotal =
                    produto.getPreco() * quantidade;

            txtSubtotal.setText(
                    String.format("%.2f", subtotal)
            );

        } catch (NumberFormatException exception) {
            txtSubtotal.setText("");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        cboProduto = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblPrecoUnitario = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("ITENS DA VENDA");

        lblVenda.setText("Venda:");

        lblProduto.setText("Produto:");

        cboProduto.addActionListener(this::cboProdutoActionPerformed);

        lblQuantidade.setText("Quantidade:");

        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
        });

        lblPrecoUnitario.setText("Preço Unitário:");

        lblSubtotal.setText("Subtotal:");

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Quantidade", "Preço Unitário", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItens.setColumnSelectionAllowed(true);
        tblItens.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblItens);
        tblItens.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPrecoUnitario)
                                        .addComponent(lblSubtotal))
                                    .addComponent(lblQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVenda, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecoUnitario)
                                    .addComponent(txtSubtotal)
                                    .addComponent(txtQuantidade)
                                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnAtualizar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(lblVenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoUnitario)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(btnLimpar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
    
        try {
        int selectedRow = tblItens.getSelectedRow();

        if (selectedRow == -1) {
            throw new RuntimeException(
                    "Selecione um item na tabela."
            );
        }

        Long id = ((Number) tblItens.getValueAt(
                selectedRow,
                0
        )).longValue();

        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente remover este item?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        itemVendaController.delete(id);

        loadTable();
        clearForm();

        JOptionPane.showMessageDialog(
                this,
                "Item removido com sucesso!"
        );

    } catch (RuntimeException exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void cboProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProdutoActionPerformed
    
        calcularSubtotalVisual();
    }//GEN-LAST:event_cboProdutoActionPerformed

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
    
        calcularSubtotalVisual();
    }//GEN-LAST:event_txtQuantidadeKeyReleased

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    
        try {
        Integer quantidade =
                Integer.valueOf(txtQuantidade.getText());

        if (itemSelecionadoId == null) {
            Produto produto =
                    (Produto) cboProduto.getSelectedItem();

            if (produto == null) {
                throw new RuntimeException(
                        "Selecione um produto."
                );
            }

            itemVendaController.adicionarItem(
                    vendaId,
                    produto.getId(),
                    quantidade
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Item adicionado com sucesso!"
            );

        } else {
            itemVendaController.update(
                    itemSelecionadoId,
                    quantidade
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Item atualizado com sucesso!"
            );
        }

        loadTable();
        clearForm();

    } catch (NumberFormatException exception) {
        JOptionPane.showMessageDialog(
                this,
                "Informe uma quantidade válida.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (RuntimeException exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    
        clearForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    
        loadTable();

    JOptionPane.showMessageDialog(
            this,
            "Lista de itens atualizada!"
    );
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    
        try {
        int selectedRow = tblItens.getSelectedRow();

        if (selectedRow == -1) {
            throw new RuntimeException(
                    "Selecione um item na tabela."
            );
        }

        Long id = ((Number) tblItens.getValueAt(
                selectedRow,
                0
        )).longValue();

        ItemVenda item = itemVendaController.findById(id)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Item da venda não encontrado."
                        )
                );

        itemSelecionadoId = item.getId();

        cboProduto.setSelectedItem(item.getProduto());
        cboProduto.setEnabled(false);

        txtQuantidade.setText(
                item.getQuantidade().toString()
        );

        txtPrecoUnitario.setText(
                String.format("%.2f", item.getPrecoUnitario())
        );

        txtSubtotal.setText(
                String.format("%.2f", item.getSubtotal())
        );
        
        btnAdicionar.setText("SALVAR");

    } catch (RuntimeException exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<Produto> cboProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrecoUnitario;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
