/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.estoquefilial.view;

/**
 *
 * @author Davi
 */
public class EstoqueFilialView extends javax.swing.JFrame {
    
    // Controller usado para acessar as operações de estoque.
    private br.com.ifba.prg03projeto.mercado.estoquefilial.controller.EstoqueFilialController estoqueFilialController;

    // Controller usado para buscar as filiais.
    private br.com.ifba.prg03projeto.mercado.filial.controller.FilialController filialController;

    // Controller usado para buscar os produtos.
    private br.com.ifba.prg03projeto.mercado.produto.controller.ProdutoController produtoController;

    // Guarda o estoque selecionado durante uma edição.
    private br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial estoqueEdicao;

    // Lista auxiliar que relaciona os itens do combo às filiais.
    private java.util.List<br.com.ifba.prg03projeto.mercado.filial.entity.Filial> listaFiliais;

    // Lista auxiliar que relaciona os itens do combo aos produtos.
    private java.util.List<br.com.ifba.prg03projeto.mercado.produto.entity.Produto> listaProdutos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstoqueFilialView.class.getName());

    /**
     * Creates new form EstoqueFilialView
     */
    
        // Carrega as filiais e os produtos nos campos de seleção.
    private void carregarCombos() {

    // Remove os itens padrões criados pelo NetBeans.
    cboFilial.removeAllItems();
    cboProduto.removeAllItems();

    // Busca todas as filiais.
    listaFiliais = filialController.findAll();

    // Adiciona o nome de cada filial no combo.
        for (br.com.ifba.prg03projeto.mercado.filial.entity.Filial filial : listaFiliais) {
        cboFilial.addItem(filial.getNome());
        }

        // Busca todos os produtos.
        listaProdutos = produtoController.findAll();

    // Adiciona o nome de cada produto no combo.
        for (br.com.ifba.prg03projeto.mercado.produto.entity.Produto produto : listaProdutos) {
        cboProduto.addItem(produto.getNome());
        }
    }
    
    // Carrega todos os registros de estoque na tabela.
    private void carregarTabela() {

    // Obtém o modelo da tabela.
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblEstoques.getModel();

    // Limpa as linhas antigas.
    modelo.setRowCount(0);

    // Busca os estoques cadastrados.
    java.util.List<br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial> lista =
            estoqueFilialController.findAll();

        // Adiciona os registros na tabela.
        for (br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial estoque : lista) {

            modelo.addRow(new Object[]{
            estoque.getId(),
            estoque.getFilial().getNome(),
            estoque.getProduto().getNome(),
            estoque.getQuantidade()
            });
        }
    }
    
    // Limpa o formulário e encerra o modo de edição.
    private void limparCampos() {

        // Seleciona o primeiro item dos combos, caso existam itens.
        if (cboFilial.getItemCount() > 0) {
        cboFilial.setSelectedIndex(0);
        }

        if (cboProduto.getItemCount() > 0) {
        cboProduto.setSelectedIndex(0);
        }

        // Limpa a quantidade.
        txtQuantidade.setText("");

        // Encerra o modo de edição.
        estoqueEdicao = null;

        // Coloca o cursor no campo quantidade.
        txtQuantidade.requestFocus();
    }
    
    
    public EstoqueFilialView() {
    
    // Inicializa os componentes visuais.
    initComponents();

    // Busca os controllers dentro do contexto do Spring.
    estoqueFilialController =
            br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
                    .getBean(br.com.ifba.prg03projeto.mercado.estoquefilial.controller.EstoqueFilialController.class);

    filialController =
            br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
                    .getBean(br.com.ifba.prg03projeto.mercado.filial.controller.FilialController.class);

    produtoController =
            br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
                    .getBean(br.com.ifba.prg03projeto.mercado.produto.controller.ProdutoController.class);

    // Inicialmente, nenhum estoque está sendo editado.
    estoqueEdicao = null;

    // Preenche os combos e a tabela.
    carregarCombos();
    carregarTabela();    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cboFilial = new javax.swing.JComboBox<>();
        cboProduto = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        sepFormularioEstoque = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoques = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setText("GERENCIAMENTO DE ESTOQUE DAS FILIAIS");

        cboFilial.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cboFilial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboProduto.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tblEstoques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Filial", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstoques);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnRemover.setText("REMOVER");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblQuantidade)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSalvar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLimpar))
                                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sepFormularioEstoque, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo)
                .addGap(16, 16, 16)
                .addComponent(cboFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addGap(35, 35, 35)
                .addComponent(sepFormularioEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    
        
    try {

        if (listaFiliais == null || listaFiliais.isEmpty()) {
            throw new RuntimeException(
                    "Cadastre pelo menos uma filial antes de cadastrar o estoque."
            );
        }

        if (listaProdutos == null || listaProdutos.isEmpty()) {
            throw new RuntimeException(
                    "Cadastre pelo menos um produto antes de cadastrar o estoque."
            );
        }

        if (txtQuantidade.getText().isBlank()) {
            throw new RuntimeException(
                    "A quantidade é obrigatória."
            );
        }

        Integer quantidade =
                Integer.parseInt(txtQuantidade.getText().trim());

        if (quantidade < 0) {
            throw new RuntimeException(
                    "A quantidade não pode ser negativa."
            );
        }

        int indiceFilial = cboFilial.getSelectedIndex();
        int indiceProduto = cboProduto.getSelectedIndex();

        br.com.ifba.prg03projeto.mercado.filial.entity.Filial filialSelecionada =
                listaFiliais.get(indiceFilial);

        br.com.ifba.prg03projeto.mercado.produto.entity.Produto produtoSelecionado =
                listaProdutos.get(indiceProduto);

        br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial estoque;

        if (estoqueEdicao == null) {
            estoque =
                    new br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial();
        } else {
            estoque = estoqueEdicao;
        }

        estoque.setFilial(filialSelecionada);
        estoque.setProduto(produtoSelecionado);
        estoque.setQuantidade(quantidade);

        if (estoqueEdicao == null) {
            estoqueFilialController.save(estoque);
        } else {
            estoqueFilialController.update(
                    estoqueEdicao.getId(),
                    estoque
            );
        }

        carregarTabela();
        limparCampos();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Estoque salvo com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "A quantidade deve ser um número inteiro válido!",
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar estoque: " + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    
    // Limpa os campos do formulário.
    limparCampos();
    
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    
    // Atualiza os combos e a tabela.
    carregarCombos();
    carregarTabela();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Estoques atualizados com sucesso!",
            "Informação",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );    
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
         int linha = tblEstoques.getSelectedRow();

    if (linha >= 0) {

        Long id = Long.parseLong(
                tblEstoques.getValueAt(linha, 0).toString()
        );

        br.com.ifba.prg03projeto.mercado.estoquefilial.entity.EstoqueFilial estoque =
                estoqueFilialController.findById(id).orElse(null);

        if (estoque != null) {

            estoqueEdicao = estoque;

            txtQuantidade.setText(
                    String.valueOf(estoque.getQuantidade())
            );

            for (int i = 0; i < listaFiliais.size(); i++) {

                if (listaFiliais.get(i).getId()
                        .equals(estoque.getFilial().getId())) {

                    cboFilial.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < listaProdutos.size(); i++) {

                if (listaProdutos.get(i).getId()
                        .equals(estoque.getProduto().getId())) {

                    cboProduto.setSelectedIndex(i);
                    break;
                }
            }

            txtQuantidade.requestFocus();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Registro de estoque não encontrado!",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione um estoque para editar!",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
    }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
    
   int linha = tblEstoques.getSelectedRow();

    if (linha >= 0) {

        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja remover este estoque?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {

            Long id = Long.parseLong(
                    tblEstoques.getValueAt(linha, 0).toString()
            );

            try {

                estoqueFilialController.delete(id);

                carregarTabela();
                limparCampos();

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Estoque removido com sucesso!",
                        "Sucesso",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );

            } catch (Exception e) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Erro ao remover estoque: " + e.getMessage(),
                        "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione um estoque para remover!",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
    }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EstoqueFilialView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboFilial;
    private javax.swing.JComboBox<String> cboProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSeparator sepFormularioEstoque;
    private javax.swing.JTable tblEstoques;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

}