/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.view;

/**
 *
 * @author Davi
 */
public class ProdutoListar extends javax.swing.JFrame {
    
    // Controller usado para acessar as operações de Produto.
    private br.com.ifba.prg03projeto.mercado.controller.ProdutoController produtoController;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoListar.class.getName());

    /**
     * Creates new form ProdutoListar
     */
    public ProdutoListar() {
        // Inicializa os componentes visuais da tela.
    initComponents();
    // Busca o ProdutoController dentro do contexto do Spring.
    produtoController = br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
            .getBean(br.com.ifba.prg03projeto.mercado.controller.ProdutoController.class);

    // Carrega os produtos cadastrados na tabela.
    carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setText("GERENCIAMENTO DE PRODUTOS");

        lblBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBusca.setText("BUSCAR:");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        btnNovo.setText("+");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Código de Barras", "Preço", "Estoque Mínimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnAtualizar)
                        .addGap(64, 64, 64)
                        .addComponent(btnEditar)
                        .addGap(81, 81, 81)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBusca)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovo))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed

    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        // Atualiza os dados da tabela.
        carregarTabela();

        // Exibe mensagem para o usuário.
        javax.swing.JOptionPane.showMessageDialog(
        this,
        "Produtos atualizados com sucesso!",
        "Informação",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        // Pega o texto digitado no campo de busca.
        String texto = txtBusca.getText();

        // Chama o método que carrega a tabela com filtro.
        carregarTabelaFiltro(texto);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        // Obtém a linha selecionada na tabela.
    int linha = tblProdutos.getSelectedRow();

    // Verifica se alguma linha foi selecionada.
    if (linha >= 0) {

    // Exibe uma caixa de confirmação antes de remover.
    int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja remover este produto?",
            "Confirmação",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    // Verifica se o usuário confirmou a remoção.
    if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {

        // Obtém o ID do produto selecionado na primeira coluna da tabela.
        Long id = Long.parseLong(tblProdutos.getValueAt(linha, 0).toString());

        // Remove o produto usando o controller.
        produtoController.deletar(id);

        // Atualiza a tabela após a remoção.
        carregarTabela();

        // Exibe mensagem de sucesso.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Produto removido com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }

    } else {

    // Exibe aviso caso nenhuma linha tenha sido selecionada.
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Selecione um produto para remover!",
            "Aviso",
            javax.swing.JOptionPane.WARNING_MESSAGE
    );
    }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // Cria a tela de cadastro de produto.
        ProdutoSave tela = new ProdutoSave();

        // Exibe a tela para o usuário.
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
  
         // Obtém a linha selecionada na tabela.
    int linha = tblProdutos.getSelectedRow();

    // Verifica se alguma linha foi selecionada.
    if (linha >= 0) {

        // Obtém o ID do produto selecionado na primeira coluna da tabela.
        Long id = Long.parseLong(tblProdutos.getValueAt(linha, 0).toString());

        // Busca o produto completo pelo ID usando o controller.
        org.springframework.http.ResponseEntity<br.com.ifba.prg03projeto.mercado.entity.Produto> resposta =
                produtoController.buscarPorId(id);

        // Pega o produto que veio dentro da resposta.
        br.com.ifba.prg03projeto.mercado.entity.Produto produtoEncontrado = resposta.getBody();

        // Verifica se o produto foi encontrado.
        if (produtoEncontrado != null) {

            // Cria a tela de edição passando o produto encontrado.
            ProdutoSave tela = new ProdutoSave(produtoEncontrado);

            // Exibe a tela de edição.
            tela.setVisible(true);

        } else {

            // Exibe mensagem caso o produto não exista mais no banco.
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Produto não encontrado!",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    } else {

        // Exibe aviso caso nenhuma linha tenha sido selecionada.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Selecione um produto para editar!",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
      }
    }//GEN-LAST:event_btnEditarActionPerformed

    // Carrega todos os produtos cadastrados na tabela.
private void carregarTabela() {

    // Pega o modelo da tabela.
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblProdutos.getModel();

    // Limpa as linhas atuais da tabela.
    modelo.setRowCount(0);

    // Busca a lista de produtos usando o controller.
    java.util.List<br.com.ifba.prg03projeto.mercado.entity.Produto> lista =
            produtoController.listarTodos(null);

    // Percorre a lista de produtos.
    for (br.com.ifba.prg03projeto.mercado.entity.Produto produto : lista) {

        // Adiciona cada produto como uma linha na tabela.
        modelo.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            produto.getCodigoBarras(),
            produto.getPreco(),
            produto.getEstoqueMinimo()
        });
    }
}

// Carrega a tabela filtrando os produtos pelo nome.
private void carregarTabelaFiltro(String texto) {

    // Pega o modelo da tabela.
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblProdutos.getModel();

    // Limpa as linhas atuais da tabela.
    modelo.setRowCount(0);

    // Busca os produtos pelo nome digitado.
    java.util.List<br.com.ifba.prg03projeto.mercado.entity.Produto> lista =
            produtoController.listarTodos(texto);

    // Percorre a lista de produtos encontrados.
    for (br.com.ifba.prg03projeto.mercado.entity.Produto produto : lista) {

        // Adiciona cada produto encontrado na tabela.
        modelo.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            produto.getCodigoBarras(),
            produto.getPreco(),
            produto.getEstoqueMinimo()
        });
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
