/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projeto.mercado.view;

/**
 *
 * @author Davi
 */
public class ProdutoSave extends javax.swing.JFrame {
    
    // Controller usado para salvar e atualizar produtos.
    private br.com.ifba.prg03projeto.mercado.controller.ProdutoController produtoController;

    // Produto usado quando a tela estiver em modo de edição.
    private br.com.ifba.prg03projeto.mercado.entity.Produto produtoEdicao;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoSave.class.getName());

    /**
     * Creates new form ProdutoSave
     */
    public ProdutoSave() {
        
    // Inicializa os componentes visuais da tela.
    initComponents();

    // Busca o ProdutoController dentro do contexto do Spring.
    produtoController = br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
            .getBean(br.com.ifba.prg03projeto.mercado.controller.ProdutoController.class);

    // Define que a tela está cadastrando um novo produto.
    produtoEdicao = null;
    }
    
    public ProdutoSave(br.com.ifba.prg03projeto.mercado.entity.Produto produto) {

    // Inicializa os componentes visuais da tela.
    initComponents();

    // Busca o ProdutoController dentro do contexto do Spring.
    produtoController = br.com.ifba.prg03projeto.mercado.Prg03sistemaMercadoApplication.contexto
            .getBean(br.com.ifba.prg03projeto.mercado.controller.ProdutoController.class);

    // Guarda o produto que será editado.
    produtoEdicao = produto;

    // Preenche os campos da tela com os dados do produto.
    txtNome.setText(produto.getNome());
    txtCodigoBarras.setText(produto.getCodigoBarras());
    txtPreco.setText(String.valueOf(produto.getPreco()));
    txtEstoqueMinimo.setText(String.valueOf(produto.getEstoqueMinimo()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblEstoqueMinimo = new javax.swing.JLabel();
        txtEstoqueMinimo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTitulo.setText("CADASTRO DE PRODUTO");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblCodigoBarras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoBarras.setText("Código de Barras:");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPreco.setText("Preço:");

        lblEstoqueMinimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstoqueMinimo.setText("Estoque Mínimo:");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPreco)
                            .addComponent(lblEstoqueMinimo)
                            .addComponent(lblCodigoBarras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstoqueMinimo)
                    .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Fecha a tela atual.
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
 
        try {

        // Cria uma variável para representar o produto que será salvo.
        br.com.ifba.prg03projeto.mercado.entity.Produto produto;

        // Se produtoEdicao for nulo, significa que estamos cadastrando um novo produto.
        if (produtoEdicao == null) {
            produto = new br.com.ifba.prg03projeto.mercado.entity.Produto();
        } else {
            // Se produtoEdicao não for nulo, significa que estamos editando um produto existente.
            produto = produtoEdicao;
        }

        // Preenche o produto com os dados digitados na tela.
        produto.setNome(txtNome.getText());
        produto.setCodigoBarras(txtCodigoBarras.getText());
        produto.setPreco(Double.parseDouble(txtPreco.getText()));
        produto.setEstoqueMinimo(Integer.parseInt(txtEstoqueMinimo.getText()));

        // Salva o produto usando o controller.
        produtoController.salvar(produto);

        // Exibe mensagem de sucesso.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Produto salvo com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        // Fecha a tela após salvar.
        this.dispose();

    } catch (NumberFormatException e) {

        // Exibe erro se preço ou estoque forem digitados incorretamente.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Preço e estoque mínimo devem ser números válidos!",
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {

        // Exibe erro genérico caso aconteça algum problema ao salvar.
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar produto: " + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdutoSave().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblEstoqueMinimo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
